# Generated by Django 5.2.4 on 2025-07-17 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ['name']},
        ),
    ]
